### Sketching
```{r}
set.seed(777)
#Fake some data for exhibition purpose
X = runif(500,min=0,max=1)
X = matrix(X,ncol=10)
X = X/rowSums(X)
print(X)
#This is a 50 by 10 dataset
```
```{r}
n = dim(X)[1]
p = dim(X)[2]
r = 0.25/ (log10(n)^(1/p))
cat(n,p,r)
```

```{r}
matProd<-function(mat1,mat2){
    #print(np.shape(mat1),np.shape(mat2))
    d = t(mat1)%*%mat2
    d1 = sum(diag(d))#this is equivalent to trace
    return (d1)
}
matProd(X,X)
```
### Row algorithm
```{r}
#Row algorithm
X = read.table('test_data1.txt')
m = 1 #pointer for exemplar
row = X[1,]
exemplars = list()
exemplars[[1]] = row
members = list()
for(t in 1:n){
    members[[t]] = c(NaN)
}
#print(exemplars)
#print(members)

myRange<-function(start,stop,step){
    if(start == stop){
        return (stop)
    }else{
        return (seq(start,stop-1,step))
    }
}

EuclideanDistance<-function(a,b){
    dist1 = sum( (a-b)^2 )
    dist1 = sqrt(dist1)
    return(dist1)
}

#print('test EuclideanDistance,', EuclideanDistance(np.array([0,0]),np.array([1,2])))
cat('\n r=',r)

#VERBOSE = TRUE for debugging
VERBOSE = TRUE
#RANDOMIZE = TRUE for randomizing the exemplars to reduce the effects of data ordering that the Leader algorithm is subject to.
RANDOMIZE = FALSE

for(i in myRange(1,n+1,1) ){
    if(VERBOSE==TRUE){
        cat('\n Handling point ',i,' out of ',n)
    }
    newExemplar = TRUE
    row = X[i,]#This should be i-th row, just i-1 since python starts counting from 0-th row.
    exemplar_ord = myRange(1,m+1,1)
    if(RANDOMIZE==TRUE){
        exemplar_ord = sample(exemplar_ord, length(exemplar_ord), replace = FALSE, prob = NULL)
    }
    #cat('>>>',exemplar_ord)
    for(j in exemplar_ord){
        d = EuclideanDistance(row, exemplars[[j]])
        if(VERBOSE==TRUE){
            cat('\n The',i,'-th point to the ',j,'-th exemplar has L^2 distance', d)
        }
        if(d<r){
            #print(members[[j]] )
            members[[j]] = c(members[[j]],i)
            newExemplar = FALSE
            break
        }
    }
    if(newExemplar==TRUE){
        m = m + 1
        if(VERBOSE==TRUE){       
            cat('\n New exemplar created. Current # of exemplars:',m)
            #cat(exemplars)
            #cat(members)
        }
        exemplars[[m]] = row
        members[[m]] = c(i)
    }
}        
print(exemplars)
print(members)
            
```
```{r}
#Reduced dataset
X_reduced = matrix(NA,nrow=0,ncol=dim(X)[2])
for(k in 1:length(exemplars)){
    if( sum( is.nan(as.numeric(exemplars[[k]]) ) )>0){
        continue
    }
    #print(exemplars[k])
    X_reduced = rbind(X_reduced, as.numeric(exemplars[[k]]) )
}    
#plot first two dimensions of original and reduced datasets.
X_original = as.matrix(X)

plot(X_original[,1], X_original[,2],main='Original dataset')

X_reduced = as.matrix(X_reduced)

plot(X_reduced[,1], X_reduced[,2],col='red',main=paste0('Row Algorithm processed dataset, r=',r))
```

